server:
  build: ./test/server
  links:
   - gnats
  environment:
    - QUEUE_NAME=qname
worker1:
  build: ./test/worker
  links:
   - gnats
  environment:
    - QUEUE_NAME=qname
    - WORKER_NAME=worker1
worker2:
  build: ./test/worker
  links:
   - gnats
  environment:
    - QUEUE_NAME=qname
    - WORKER_NAME=worker2
gnats:
  image: apcera/gnatsd

